spring:
  application:
    name: currency-exchange
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
      sample-api:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
